// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/api/admin/_middleware.ts";
import * as $1 from "./routes/api/admin/device.ts";
import * as $2 from "./routes/api/auth/github.ts";
import * as $3 from "./routes/api/device/_middleware.ts";
import * as $4 from "./routes/api/device/config.ts";
import * as $5 from "./routes/api/device/info.ts";
import * as $6 from "./routes/api/joke.ts";
import * as $7 from "./routes/ca.crt.ts";
import * as $8 from "./routes/dashboard.tsx";
import * as $9 from "./routes/index.tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/SupernovaAppIsland.tsx";

const manifest = {
  routes: {
    "./routes/api/admin/_middleware.ts": $0,
    "./routes/api/admin/device.ts": $1,
    "./routes/api/auth/github.ts": $2,
    "./routes/api/device/_middleware.ts": $3,
    "./routes/api/device/config.ts": $4,
    "./routes/api/device/info.ts": $5,
    "./routes/api/joke.ts": $6,
    "./routes/ca.crt.ts": $7,
    "./routes/dashboard.tsx": $8,
    "./routes/index.tsx": $9,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/SupernovaAppIsland.tsx": $$1,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
